### ISSUE TITLE
Back-End for Database

### ISSUE THREAD

**Issue by Harmain1233** [Harmain1233/YourDigitalPlanner#4]
Here’s a concise to-do list for the developer:

### To-Do List

- [ ] **Implement User Authentication**
  - Create user login with JWT/OAuth
  - Set up `Users` table/collection:
    - `user_id` (UUID)
    - `username` (unique)
    - `email` (unique)
    - `password_hash` 

- [ ] **Create Task Tracking System**
  - Set up `Tasks` table/collection:
    - `task_id` (UUID)
    - `user_id` (FK to Users)
    - `task_name`
    - `is_completed` (boolean)
    - `created_at`
    - `updated_at`

- [ ] **Store User Info**
  - Track number of tasks and completion status.
